### ISSUE TITLE
Build process / tools roadmap

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1419]
- [ ] Build UMD module(s) and publish with the npm package.  This allows TerriaJS to be used without Webpack.
  - [x] Generate UMD module(s).  `gulp build-libs`.
  - [ ] Add tests (or at least a demo project) that demonstrates the UMD module works.
- [ ] NPM Publish built CSS along with built UMD module.
- [ ] Make TerriaJS work with Browserify again.  One challenge is that we're now loading HTML and XML using the Webpack `raw-loader` (so `require('./whatever.xml')`) instead of the Browserify `brfs` (so `require('fs').readFileSync(__dirname + './whatever.xml', 'utf8')`).  Another is the Babel transformation.  Ideally we'd just publish individual modules that have already been transformed by loaders but _not_ combined.
- [x] Let Webpack build our CSS.
  - [x] Use CSS modules?
- [x] Add support for [hot module replacement](https://webpack.github.io/docs/hot-module-replacement.html) so we need to reload the app less often
- [ ] Enable use of [Flow](http://flowtype.org/)
- [x] Separate our build into separate [chunks](https://webpack.github.io/docs/code-splitting.html).  e.g. one for Cesium, one for Leaflet, one for WPS support, etc.
- [ ] Tighten up eslint rules.  Currently they're chosen primarily to not flag anything that jshint didn't already flag (so we get a clean report without changing all our code).  We should evaluate what rules we want to turn back on.
- [x] Use the Webpack dev server to get faster builds and maybe other benefits.

**Comment by kring** [comment]
Not much here that we need an issue to track, closing.
