### ISSUE TITLE
NewUI Mobile Issues

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1781]
# In rough groupings of priority:
### High
- [x] Scrolling the catalogue on iOS moves the map underneath instead
### Med
- [x] The marker showing the selected location search result doesn't appear on mobile.
- [x] Remove the quick add button on mobile, replace it with a chevron pointing right
- [x] Geolocation button needs to be bigger and spaced evenly from the side of the screen
- [x] The feature info comes up under the location button (but Kevin has fixed it I think?)
- [x] Top row of feature info should be the same height as the top row of the catalog (the row with the "Done" button) so that the close button can be tapped
- [x] Top row of selected layers should also be that height so that the show/hide button can be tapped
- [x] Search button needs to be wider and have space to the left of it (a divider) to make it more tappable.
### Low
- [x] Catalog items need more padding above and below
- [ ] ~~The add-to/remove-from-map button on the preview screen would be better if it were slightly thinner than the screen, and was white when not added and dark grey when added~~ Phil changed his mind on this one.
- [x] Remove the icon from the branding to save space - possibly responsively re-introduce it as width increases?
- [x] Change the DATA button to Data
- [x] The menu icon is aligned slightly wrong on iOS
- [x] The padding on the bar at the top of the screen is slightly wrong on iOS
- [x] The small number indicating how many layers are visible should change to a full-size number as width becomes available.
- [x] The opacity slider should be full width
- [] ~~The search box doesn't need the black frame around it.~~
### Super-Low
- [x] Search doesn't work at all :)

**Comment by kring** [comment]
And then minor things like "search doesn't work at all". :)

**Comment by AlexGilleran** [comment]
Added :p

**Comment by kring** [comment]
I'm doing a pass right now that should fix many of these.

**Comment by kring** [comment]
> Geolocation button needs to be bigger and spaced evenly from the side of the screen

@philipgrimmett evenly from what?  Do you mean the same distance from the right and bottom?

**Comment by kring** [comment]
> Scrolling the catalogue on iOS moves the map underneath instead

Hopefully this is fixed, but someone will need to try it on iOS.  On Android scrolling just didn't work at all.

**Comment by AlexGilleran** [comment]
> Scrolling the catalogue on iOS moves the map underneath instead

Scrolling is now fixed but it still does a weird thing where the hover state triggers on the item that your finger's over as you scroll.

**Comment by AlexGilleran** [comment]
Amazing work killing so many of these so quickly btw 😬

**Comment by kring** [comment]
Done enough for this release!  Moving out of the milestone.

**Comment by chloeleichen** [comment]
> The small number indicating how many layers are visible should change to a full-size number as width becomes available.

What does this mean?

**Comment by philipgrimmett** [comment]
@chloeleichen when a data set is added, a number will appear to the right of the eye button, but at the moment the number is tiny (when two data sets are on it looks like _eye_ squared). Ideally it would be a full-size number (~12-13px?)

**Comment by chloeleichen** [comment]
>  The search box doesn't need the black frame around it.

I think the search on mobile in general could look better, any suggestions @philipgrimmett ?
