### ISSUE TITLE
[EPIC] Drawing tool improvements (v2) 

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1981]
These are a list of improvements to be made to the drawing tool in TerriaJS that currently allows drawing lines and polygons. The tool is used for selecting areas and passing to WPS functions, as well as measuring lines, so any changes should bear in mind both contexts.
- [ ] Tooltip on the cursor, with instructions "Click to start drawing" **UX/UI review recommendation**
- [ ] Attach optional info box to end of polygon in progress to show updates **UX/UI review recommendation**
- [ ] Have ‘Done’ button attached to start tool **UX/UI review recommendation**
- [ ] Close complex polygon without having it flicker
- [ ] Needs to draw arc in Leaflet rather than straight line (look into how Cesium is subsampling the line and do the same, for consistency if nothing else).
- [x] Drag points around to adjust line **UX/UI review recommendation**
- [ ] Allow adding points midline (draw point on line, slightly transparent, which slides along line and becomes real if user clicks it). **UX/UI review recommendation (I think)**
- [ ] Solve pointy corners in 3D lines issue, see image below. 1: lines are distorted when angle is too steep. 2: even with a more moderate angle there's a dark spur on corner.

![sharp_corners_look_bad](https://cloud.githubusercontent.com/assets/3466267/17921808/297e4632-6a1f-11e6-862d-7768e7b2cdd3.png)
