### ISSUE TITLE
Model Architecture: Implement SdmxCatalogItem

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3524]

**Comment by soyarsauce** [comment]
Ping Rowan or Nanda if the master sdmx stuff is still unclear

**Comment by AnaBelgun** [comment]
ABS has released the latest data api based on SDMX JSON v2.1 
Here are the details to test: https://docs.google.com/document/d/1J3con-CBdBGlQLSelZ_eYwesX2cjYI5UnGfSLMNZg9o/edit#
ABS would like for an APIkey to be used with the calls

**Comment by nf-s** [comment]
## SDMX learning materials

- [Learning about SDMX Basics](https://sdmx.org/?page_id=2555/)
- [Framework doc](https://sdmx.org/wp-content/uploads/SDMX_2-1_SECTION_1_Framework_2020-07.pdf)
- [Information model](https://statswiki.unece.org/display/ClickSDMX/Clickable+SDMX+Home)
- [User Guide](https://sdmx.org/wp-content/uploads/SDMX_2-1_User_Guide_draft_0-1.pdf)
- https://ec.europa.eu/eurostat/web/sdmx-infospace/welcome
- https://www.bis.org/statistics/sdmx.htm

REST cheat sheets:

https://raw.githubusercontent.com/sdmx-twg/sdmx-rest/master/v2_1/ws/rest/docs/rest_cheat_sheet.pdf
https://sis-cc.gitlab.io/dotstatsuite-documentation/using-api/restful/

## Reference

- Information Model - https://github.com/sdmx-twg/sdmx-im/blob/I1-doc/docs/source/Sections/Section1/SDMX_2-1_SECTION_1_Framework.rst#the-sdmx-view-of-statistical-exchange
- https://github.com/sdmx-twg/sdmx-rest
- https://github.com/sdmx-twg/sdmx-csv
- https://github.com/sdmx-twg/sdmx-json

For structure messages see - https://github.com/sdmx-twg/sdmx-json/blob/structure-message-release/structure-message/docs/1-sdmx-json-field-guide.md#agencyscheme

## SDMX group structure

Something similar to this - https://ilostat.ilo.org/data/sdmx-query-builder/

https://registry.sdmx.org/webservice/data.html

https://github.com/sdmx-twg/sdmx-json/blob/structure-message-release/structure-message/requirements/browse-by-topic.md

### Steps:

- Get agencyIds https://stats-nsi-stable.pacificdata.org/rest/agencyscheme/
- ~Get categoryschemes https://stats-nsi-stable.pacificdata.org/rest/categoryscheme/SPC~
  - ~Maps category schemes to categories~
- ~Get categories https://stats-nsi-stable.pacificdata.org/rest/categorisation/SPC/~
  - ~Maps categories to dataflows~
- ~Get dataflows https://stats-nsi-stable.pacificdata.org/rest/dataflow/SPC/~
- **NO!** This will return categoryschemes/categories dataflows instead - https://stats-nsi-stable.pacificdata.org/rest/categoryscheme?references=parentsandsiblings
- Get datastructure https://stats-nsi-stable.pacificdata.org/rest/datastructure/SPC/DSD_COMMODITY_PRICES
- Get data! https://stats-nsi-stable.pacificdata.org/rest/data/DF_SDG_17


## APIs

https://sdd-dotstat-api-gateway.portal.azure-api.net/concepts

See https://github.com/sdmx-twg/sdmx-rest for more

## Thoughts

Maybe use sdmx-csv instead? - see https://github.com/sdmx-twg/sdmx-csv/blob/master/data-message/docs/sdmx-csv-field-guide.md

## Js libs

Started with [`sdmx-rest`](https://github.com/sdmx-twg/sdmx-rest), but is only really useful for creating requests.

Master used [`sdmxjsonlib`](https://github.com/airosa/sdmxjsonlib/), but it is quite basic, isn't maintained

[`dotstatsuite-sdmxjs`](https://gitlab.com/sis-cc/.stat-suite/dotstatsuite-sdmxjs) which is used by .stat suite - looks like the most useful.

At this stage I am not using any libs - as the type definitions do all the hard work. I may reconsider this as I create the `SdmxJsonCatalogItem`

**Comment by nf-s** [comment]
I have types for all SDMX data messages, and some SDMX structure messages - https://github.com/nf-s/sdmx-json-types

**Comment by nf-s** [comment]
Groups are now working in this order:
- Agency
- Category scheme
- Category
- Dataflow

**Comment by nf-s** [comment]
![image](https://user-images.githubusercontent.com/6187649/90851973-9535b000-e3b9-11ea-99bd-e8d098b9a44a.png)

**Comment by nf-s** [comment]
## SDMX item structure:

- Codelist
- Data flow:
  - Data structure
    - Concepts
  - Content Constraints

All of this information is given by = https://stats-nsi-stable.pacificdata.org/rest/dataflow/SPC/DF_CPI?references=all
It may be more efficient to fetch Codelists and concepts at the SdmxGroup level - but this is easier for the moment

**Comment by nf-s** [comment]
Very basic SDMX item is now working 
![image](https://user-images.githubusercontent.com/6187649/91048396-f7fba580-e65e-11ea-92d0-98dd225ea479.png)

Some TODOs:

- [x] - Add region mapping support
- [x] - Deal with measurement dimensions
- [x] - Deal with time dimensions - see #4674 
- [x] - Improve compatibility with other SDMX-json services
- [x] - Test with ABS 
- [x] - ~Fix dimension options (currently it shows union of all contentContraints + cubeRegions => so some combinations of values won't return anything)~ I don't think this matters for the moment, the `cubeRegions` don't seem 100% for most layers
- [x] - Simplify generated type definitions
- [x] - Support nested categories

**Comment by nf-s** [comment]
Basic region mapping is working (time selector isn't working yet)
![image](https://user-images.githubusercontent.com/6187649/91152686-a1e03e00-e702-11ea-9a15-755b0310fdc2.png)

But this isn't a very good visualisation for pacific countries...

**Comment by nf-s** [comment]
Issue with region-mapping https://github.com/TerriaJS/terriajs/issues/4676 and time-dimension #4674

**Comment by nf-s** [comment]
ABS region mapping now working
![image](https://user-images.githubusercontent.com/6187649/91550131-6a27ff00-e96b-11ea-9ef7-3d3e1f4f5b02.png)

**Comment by nf-s** [comment]
It is now working on CI-deployment http://ci.terria.io/sdmx-next/#clean&https://gist.githubusercontent.com/nf-s/24b9288c6cdb6ba41d12f3d269318a0d/raw/c5ed64071c8a651ae458b4c0d3dc79c8618cb86d/sdmx.json

Not all layers will work (especially some ABS ones), but quite a few do.
Note issues with region-mapping #4676 and time-dimension #4674

**Comment by nf-s** [comment]
Some layers will require setting `conceptTraits` to work correctly - (usually for region-mapping). 

## Setting up regions


Information about that can be found here - https://github.com/TerriaJS/terriajs/blob/c351cb6c598ce66dc1ed373e7cc811a88766f0c5/lib/Traits/SdmxCommonTraits.ts

> RegionType is determined by sdmxJsonDataflowStratum.column in this order:
>  1.  `conceptTraits.regionType`
>  2.  if `conceptTraits.type === 'region'` and there exists another conceptTraits with `type === 'region-type'` in the datastructure, therefore region-type will be set from this concept
>  3. the dimension id
>  4. the concept name
>  5. the concept id (the actual string, not URN form)

### For example SPC - Option 1 above

The following catalog json specifies that the `CS_COMMON(2.0).GEO_PICT` concept corresponds to regionType `CNT2` (2-digit country code). So whenever this concept is used in a dataflow, the region type will be set to `CNT2`

```json
 "conceptOverrides": [
        {
          "id": "urn:sdmx:org.sdmx.infomodel.conceptscheme.Concept=SPC:CS_COMMON(2.0).GEO_PICT",
          "type": "region",
          "regionType": "CNT2"
        },
...
```

### Another example, ABS - Option 2 above

Some dataflows use `REGION_TYPE` concept to specify the region type, and `REGION` concept to specify the region. If the `REGION_TYPE` concept is found within a dataflow, it's `selectedId` will be used as the `regionType` for the `REGION` concept.

```json
 "conceptOverrides": [
        {
          "id": "urn:sdmx:org.sdmx.infomodel.conceptscheme.Concept=ABS:CS_C16_COMMON(1.0.0).REGION_TYPE",
          "type": "region-type",
          "selectedId": "SA3"
        },
        {
          "id": "urn:sdmx:org.sdmx.infomodel.conceptscheme.Concept=ABS:CS_C16_COMMON(1.0.0).REGION",
          "type": "region"
        },
...
```

### Options 3 - 5

These are a bit more obvious, and are kind of handled in the same way a column title is used to find the corresponding `regionType` - for example `lga_code_2016` - but it uses the first option which matches a valid `regionType`

## Other `ConceptTraits`

`ConceptTraits` extends `DimensionTraits` so you also get the following properties you can override:

```ts
@primitiveTrait({
    type: "string",
    name: "Name",
    description: "Dimension name (human-readable)"
  })
  name?: string;

  @objectArrayTrait({
    type: DimensionOptionTraits,
    idProperty: "id",
    name: "Options",
    description: "Dimension options"
  })
  options?: DimensionOptionTraits[];

  @primitiveTrait({
    type: "string",
    name: "Selected ID",
    description: "Selected Option's ID"
  })
  selectedId?: string;

  @primitiveTrait({
    type: "boolean",
    name: "Allow undefined",
    description: "Allow dimension to be undefined"
  })
  allowUndefined?: boolean;

  @primitiveTrait({
    type: "boolean",
    name: "Disable dimension",
    description: "Hides dimension"
  })
  disable?: boolean;
```

**Comment by nf-s** [comment]
Some TODOs:

- [x] Add EEZ regions for pacific region mapping - https://github.com/PacificCommunity/Terria-PacificMap/blob/master/wwwroot/data/regionMapping.json - this might fix antimeridian issue
- [x] Look into weird local terriajs-server proxy issue with api.data.abs.gov.au/dataflow/ - it returns HTTP 400 error:
> HTTP/1.1 400 Bad Request
X-Powered-By: Express
Access-Control-Allow-Origin: *
content-type: application/json; charset=utf-8
content-length: 0
date: Wed, 02 Sep 2020 05:36:34 GMT
x-amzn-requestid: 43faaed7-84af-458b-8e09-e865338dd2cf
x-amzn-remapped-content-length: 0
x-amzn-remapped-connection: Keep-Alive
x-amz-apigw-id: SORXXGyGSwMFYaw=
x-amzn-remapped-server: BigIP
x-cache: Error from cloudfront
via: 1.1 aee00c65edc39a007fb4a2fe5f4541d6.cloudfront.net (CloudFront)
x-amz-cf-pop: SYD1-C1
x-amz-cf-id: HCKu6JPsdHohx9V71EPRandj5NYujfJtdj9Q_RmJiBvLMvq82JBDaQ==
Vary: Accept-Encoding
Connection: keep-alive

**Comment by nf-s** [comment]
HTTP 400 issue may be related to lack of IPv6 support.

**Comment by nf-s** [comment]
I might add `ColumnTraits` to `ConceptTraits` so you can directly add column style/etc... properties to concepts

**Comment by nf-s** [comment]
# Update!

I consider this finished (as a first pass anyway) - I just need to write tests.

## There are a few things missing from master implementation:

- [ ] Ability to select multiple values for a given dimension
- [ ] Aggregate dimension values (eg sum or show percentage of total)

## Other possible features

- [ ] Add `ColumnTraits` to `ConceptTraits`

**Comment by soyarsauce** [comment]
rowan: test some of the ways we use in nationalmap for it - and if we get the same results then we are good.

nick: main difference w/ v7 implementation, we have sdmx groups, instead of creating a catalog item for every single data flow
ideally we just 'browse a sdmx'

@nf-s to update post-Wedneday

**Comment by nf-s** [comment]
# Feedback from meeting

- [x] - Fix feature info template - so we can see more useful info when you select a region
- [x] - Click region to see time series
- [x] - ^ sync timeseries with region-mapping (click on chart to show time)
- [ ] - Sum/Proportion for Concepts (eg sex - show proportion of men/total) - be careful to only allow this for certain concepts
- [x] - ABS category schemes incoming
- [X] - ~SDMX from CKAN?~ NO NO
- [x] - EZ pacific region vector tiles

**Comment by nf-s** [comment]
# Other thoughts

- [ ] Start using ABS API key
- [x] Compare with National Map SDMX
- [x] Get into next pacific map release

**Comment by nf-s** [comment]
I'm going to close this as https://github.com/TerriaJS/terriajs/pull/4659 has been merged. We can create new issue(s) after we have received more feedback - I will make issues on current feedback

**Comment by nf-s** [comment]
I'm going to re-open this for - NationalMap - Beta release (V8) - Feb 2021  https://github.com/TerriaJS/nationalmap/issues/997

I wanted to create separate tickets, but I didn't have time

**Comment by nf-s** [comment]
- [x] Add column title traits for feature info

This is not great:
![image](https://user-images.githubusercontent.com/6187649/106871919-e0a10800-6726-11eb-84c4-c23b0b08eb98.png)

Maybe write a featureInfoTemplate using region feature info from https://github.com/TerriaJS/terriajs/pull/5211

**Comment by nf-s** [comment]
- [x] Make sure loading icon works when selectors change values

**Comment by nf-s** [comment]
- [ ] Add way to toggle manual region mapping (in tool menu thing)

**Comment by nf-s** [comment]
- [ ] #4675 Object array trait ordering

**Comment by nf-s** [comment]
## Update!

![image](https://user-images.githubusercontent.com/6187649/107373871-1a18af80-6b3b-11eb-9cd6-0155ed582941.png)

- "Export" will now return raw SDMX-CSV data
- Add `TableMixin` time-series chart for region mapping
- Add `SdmxDataflowStratum.featureInfoTemplate` to improve feature info section
- Improve SDMX timeseries chart
- Fix loader/spinner
- Renamed `conceptOverrides` to `modelOverrides` - and added codelist override support
- Added `regionTypeReplacements` - so manually override detected `regionTypes`
- Added `primary-measure-descriptor` `modelOverride` type - this will set the primary measure title based on selected value of primary measure descriptor dimension
- Set time column manually
- Fix regionType bugs
- Add sdmx data error message

**Comment by nf-s** [comment]
URL to test it out!  
http://ci.terria.io/sdmx-fixes-loading/#clean&https://gist.githubusercontent.com/nf-s/1e05f005a93d7b9ab6f1723b8b40d1d2/raw/f74e8c68f849db10cccfa96b05943cdb9cdb635b/abs-sdmx.json

**Known dataset issues**

- RIME by region of arrival by departure, SA4 and above (ASGS 2016), 2016-17 onwards - Not sure how to represent

- Consumer Price Index - Time period issue (2020-Q1...)

- Population Projections... - GCCSA region issue - region mapping type not supported by Terria

- Australian Census Longitudinal Dataset (ACLD): Tenure and landlord type, 2006-2011 - using "urn:sdmx:org.sdmx.infomodel.codelist.Codelist=ABS:CL_ASGS_2011(1.0.0)" but doesn't have region_type dimension

**Comment by nf-s** [comment]
## TODO

- [x] Region mapping for Land Management Practices Survey, 2011-12

## Future Improvements

### Chart "expanding"

At the moment, when you expand a chart you don't get any information about dimensions 

<img src="https://user-images.githubusercontent.com/6187649/109102695-84f1f980-777d-11eb-930e-ec162b0cee58.png" width="400px"/>

![image](https://user-images.githubusercontent.com/6187649/109102671-786da100-777d-11eb-8090-e22fbabd2465.png)

**Comment by nf-s** [comment]
## ABS Dataflow issues

### Supply Use Table

`UNIT_MEASURE` is set to `OBS_COMMENT` concept.  
https://api.data.abs.gov.au/dataflow/ABS/ABS_SU_TABLE_2018?references=all

**Comment by nf-s** [comment]
## Issues

- [x] "Expanding" charts will overwrite existing charts
- [x] Hide date/time selector if no region mapping

**Comment by nf-s** [comment]
Closing again! 
Due to https://github.com/TerriaJS/terriajs/pull/5234
