### ISSUE TITLE
Story feature v2.0 - Aug 21 Release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3532]
The Story proved to be one the most popular features especially used for demonstrations and sharing. 
User journeys that Story v2.0 is aiming to improve are for Story creators and Story users. 

Technical prerequisites for story v2.0:
- [x] https://github.com/TerriaJS/terriajs/issues/5577

**1) Story creators**
Main objectives (in priority order): 
- Stability;  confidence that once shared it will work longer than the moment it was shared 

As a story creator I would like to share my story and be confident that it will work when users are accessing the share link; should elements / scenes of the story (not under my control) will break, the users should have clear error message and a graceful transitions to scenes that work. 
- [x] https://github.com/terriajs/terriajs/issues/5427 - **Priority 1**
- [x] https://github.com/terriajs/terriajs/issues/4692 **Priority 2**
- [x] https://github.com/TerriaJS/terriajs/issues/5646 - **Priority 3**
- [x] https://github.com/terriajs/terriajs/issues/4620 - **Priority 7**
- [x] https://github.com/terriajs/terriajs/issues/3827 **Priority 5**
___________________________________________________________________________________________________ 
- [ ] https://github.com/terriajs/terriajs/issues/3279 - **Priority 4**
- [ ] https://github.com/TerriaJS/terriajs/issues/5595 - **Priority 6**
- [ ] https://github.com/TerriaJS/terriajs/issues/5596 - **Priority 8**
________________________________________________________________________________________________________
- [x] https://github.com/TerriaJS/terriajs/issues/5598
- [x] https://github.com/terriajs/terriajs/issues/3539
- [x] https://github.com/terriajs/terriajs/issues/3535
- [ ] https://github.com/terriajs/terriajs/issues/5228 

- Fix major issues: charts interaction, split map
- [x] https://github.com/terriajs/de-australia-map/issues/97
- [x] https://github.com/terriajs/terriajs/issues/4709

**2) End users - consumers of stories**
Main objectives 
- Clarity on tasks and messages (i.e. previews for next scenes, error messages, popups interfering with story mode) 
- [x] https://github.com/terriajs/terriajs/issues/4432
- [x] https://github.com/terriajs/terriajs/issues/4793

- Clarity on where users are in relation to usual map functionality (i.e. active story mode, exiting story mode - resuming story mode, exiting - no resuming/closing etc.)
- [x] https://github.com/terriajs/terriajs/issues/4119
- [x] https://github.com/terriajs/vic-digital-twin/issues/99
- [ ] https://github.com/terriajs/terriajs/issues/4210
- [ ] https://github.com/TerriaJS/terriajs/issues/5597
- [ ] https://github.com/terriajs/terriajs/issues/5463

**Comment by robbibt** [comment]
One feature I would love is the ability to supress all Terria popups for specific stories (particularly those that are intended to be self-describing). For example, when visiting the [DEA Coastlines story](https://maps.dea.ga.gov.au/#share=s-DEACoastlines&playStory=1), first-time users are presented with the "Let's get you started" pop-up which appears on top of the story - we've had a few people come to us confused because pressing the big "Explore map data" button takes them away from the Coastlines story itself. 

This could be solved by being able to toggle a "Suppress getting started" button when creating the story. Alternatively, perhaps that popup could be presented after the story is complete, not before?

**Comment by robbibt** [comment]
Another issue we had with the DEA Coastlines story was that Terria currently seems to show different zoom level depending on the size of the screen the story is viewed on. For example, the DEA Coastlines layers have zoom-dependent symbology that transition at certain zoom levels. If a story is created on a large screen, but then viewed on a smaller screen (i.e. laptop or mobile), the difference in zoom levels causes different layers to show up than was originally intended (e.g. points showing when annual coastlines were meant to show instead).

**Comment by AnaBelgun** [comment]
@AnaBelgun to coordinate a meeting for story v2.0 refinement

**Comment by AnaBelgun** [comment]
Problem brief brief on making stories break less. 
Currently the stories created in v7 would easily break in v8 due to migration issues.
The stories created in v8 would still break due to one or combination of reasons:

- data service removed / decommissioned by the custodian
- data service url modified by the custodian without decommissioning
- bugs due to latest software releases

Breaking stories create a very bad user experience which can be addressed by: 

- making the sharelinks more reliable
- better handling the url changes
- better handling of error messages (differentiation between data and software bugs)
- graceful transition to other data. scenes when data is decommissioned
- better handling of re-arranging catalogue (when not decommissioning, removing datasets) - Story v2.0 - - handle re-arranging catalogue not to break sharelinks #5646

**Comment by AnaBelgun** [comment]
Update 12 Apr 22: 
- this epic has been closed and remaining tickets transferred to Story v3.0 epic
