### ISSUE TITLE
Model architecture: Share & story migration

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#3654]
As a map owner
I want my v8 map to load old v7 generated share links
So that I don't break old links

Other notes:
- terriajs-server is already being used when loading share links, so it makes most sense to do this at the terriajs server.
- dragging catalogs into browser
- non-server-side-share-links (JSON in URL - this is unofficially supported, so do we officially support this? NO)
- properties that v8 doesn't understand
- catalog types that v8 doesn't understand
- any viewstate-ey things that aren't implemented
- any other config
- (what other warnings we don't even need to throw warnings about?)
- v7 shares with init sources shared

### DoD:
- [x] Unit test written (if applicable)
- [x] Works on mobile (or deliberately disabled for mobile)
- [ ] Code/peer reviewed (if didn't pair)
- [ ] Relevant docs are updated
- [x] Previewable/deployed to dev (see separation of deployments)
- [x] Previewable/deployed to test (see separation of deployments)
- [x] (If a map-specific ticket) Issue linked to a release ticket

### Acceptance Criteria:
- [x] Loading old share links (~0.0.05) into a v8 map works
- [x] Server passes some message to client so that the payload has a "this used to be v7"
- [x] A UI warning to show that we've detected a v7 link was loaded in and that it may not work as intended
- [x] v7 share data is applied at user strata level

As a second pass
- [x] v7 share links containing stories will turn into working v8 stories

### Background context

We've versioned mobx branch shares to `8.0.0`, while non-mobx is on `0.0.05` - we should use this information to transform and preserve functionality of old share links as much as possible

```
Wing Ho [2:41 PM]
so something that came up on gitter - is mobx going to break
`0.0.05` share links? i haven't looked at how `8.0.0` (mobx versioned constant)
differs but i imagine we do some transformation from 0.0.05->8.0.0 within
terriajs, before putting it through the mobx logic?

Stephen Davies [3:29 PM]
@soyarsauce I’m not sure we’ve really thought it out,
but I think the result will be no; all share links will be broken (edited) 


Wing Ho [3:31 PM]
yeah that's what i mean, we put the payload through some sort
of migration when we see 0.0.05 to transform it into mobx-eatable-format?

Stephen Davies [3:32 PM]
Possibly for buckets we control we could convert all
the share data to mobx-compatible while converting the catalog of an instance
But a lot of our share data is mixed Maybe IDs will save a lot of it and we can
preserve what items are enabled, the camera angle and the time

Wing Ho [3:34 PM]
i wouldn't want to change the content in buckets themselves -
they should remain immutable, and we bundle the transformer for 0.0.05->8.0.0
either in terriajs-server or in terriajs itself

Stephen Davies [3:38 PM]
Yeash, I guess a simple transformer that would work is
iterate through all the items, guess ids for shared items without ids, apply a
transformation specific to the item’s type that tries to preserve as much of the
state about the catalog item while outputting new share attributes

Wing Ho [3:44 PM]
:+1:  sounds like a post-DT-pre-bigbangmerge piece of work
```

**Comment by soyarsauce** [comment]
Also needs to work for story

**Comment by nf-s** [comment]
# Update!

I have basic share-conversion working with enabled csv catalog items + common properties which haven't changes (camera position...)

## PRs

- TerriaJS - https://github.com/TerriaJS/terriajs/pull/4735
- TerriaJS-server - https://github.com/TerriaJS/terriajs-server/pull/119
- Catalog-converter - https://github.com/TerriaJS/catalog-converter/pull/11

**Comment by nf-s** [comment]
# Update 2!

It is a bit ugly, but a start!

![image](https://user-images.githubusercontent.com/6187649/92872315-39ef5e80-f449-11ea-8878-bd6113e3c9de.png)

**Comment by nf-s** [comment]
TODO:

- [x] Test more examples of catalogs (test stories)
- [x] Write unit tests
- [ ] Support client-side?
- [ ] Handle URL initSources?

**Comment by nf-s** [comment]
Added story support!

**Comment by nf-s** [comment]
Order of things todo:

- [x] Fix test errors in TerriaJS PR ...
- [x] Terriajs PR - https://github.com/TerriaJS/terriajs/pull/4735
- [x] Write share data tests in `catalog-converter`
- [x] Catalog-converter PR - https://github.com/TerriaJS/catalog-converter/pull/11
- [x] Fix `terriajs-server` test suite - https://github.com/TerriaJS/terriajs-server/pull/119
- [x] TerriaJS-server PR - https://github.com/TerriaJS/terriajs-server/pull/119
- [x] Review Multi-tenancy PR - https://github.com/terriajs/terriajs-server/issues/120

Related issues

- https://github.com/TerriaJS/catalog-converter/issues/7

**Comment by nf-s** [comment]
For my assumptions on share/catalog structure - see https://github.com/TerriaJS/catalog-converter/pull/11#issuecomment-694142562

**Comment by nf-s** [comment]
# Update!

Works with user added data (in or not in workbench) - but it doesn't work with nested user added groups (eg WMS-group).
To fix this I need to go through and convert IDs

**Comment by soyarsauce** [comment]
To assist with the ID problem perhaps we need to think about allowing for "previous known IDs or names" when we are migrating catalogs - just a fleeting thought

**Comment by soyarsauce** [comment]
See: https://github.com/TerriaJS/terriajs/issues/4774

**Comment by na9da** [comment]
Missing properties for Pacific Map ([spc.json](http://pacificmap.terria.io/proxy/_0s/https://terria-apps.s3-ap-southeast-2.amazonaws.com/pacific-map/spc.json))
```
      # These ones are deprecated and can be written instead using `filterQuery`. 
      # Probably not worth converting as the item gets used only in a few places (Rowan)
      1 allowEntireWmsServers (CKAN)
      1 filterByWmsGetCapabilities (CKAN)
      1 includeCsv (CKAN, deprecated)
      1 includeEsriFeatureServer (CKAN, deprecated)
      1 includeEsriMapServer (CKAN, deprecated)
      1 includeGeoJson (CKAN, deprecated)
      1 includeKml (CKAN, deprecated)
      1 includeWfs (CKAN, deprecated)
      1 includeWms (CKAN, deprecated)


      7 isCsvForCharting (CSV, not ported)
      1 minimumMaxScaleDenominator (CKAN, not ported)
```

Missing properties for DE Africa ([africa.json](https://maps.digitalearth.africa/proxy/_60s/https://raw.githubusercontent.com/digitalearthafrica/config/master/terria/africa.json))

```
      5 featureInfoTemplate.formats
     17 ignoreUnknownTileErrors
     12 preserveOrder
     17 tileErrorThresholdBeforeDisabling
```
DE Aus ([dea-maps.json](https://maps.dea.ga.gov.au/proxy/_60s/https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/terria/dea-maps.json))

```
      3 chartDisclaimer (add support in catalog-converter)
     18 featureInfoTemplate.formats
      3 id
     58 ignoreUnknownTileErrors
     53 leafletUpdateInterval (catalog-converter#9)
      3 legendUrl
      2 legendUrls
     29 preserveOrder
      3 shortReport
      1 template
      1 zoomOnEnable
```

DE Aus ([terria-cube.json](https://maps.dea.ga.gov.au/init/terria-cube.json))

```
      1 custodian
      2 tryToLoadObservationData
```

**Comment by na9da** [comment]
`ignoreUnknownTileErrors` & `tileErrorThresholdBeforeDisabling` will be fixed by - https://github.com/TerriaJS/terriajs/pull/4730

**Comment by nf-s** [comment]
## V7 catalog item properties missing from `catalog-converter` 
**(or missing entirely from V8)**

Looks good!

We can ignore Pacific Map CSV errors - those layers are replaced by SDMX

### Catalog Member

- id ?
- shortReport

### WMS

- legendUrl
- zoomOnEnable
- featureInfoTemplate.formats
- leafletUpdateInterval (Fixed https://github.com/TerriaJS/catalog-converter/pull/9)
- ignoreUnknownTileErrors (https://github.com/TerriaJS/terriajs/pull/4730)
- chartDisclaimer (add support in catalog converter)
- legendUrls
- tileErrorThresholdBeforeDisabling (https://github.com/TerriaJS/terriajs/pull/4730)

### Group
- custodian
- preserveOrder

### SOS
- tryToLoadObservationData (not ported)

### CKAN

- includeCsv
- includeGeoJson
- includeKml
- includeWms
- includeWfs
- includeEsriMapServer
- includeEsriFeatureServer
- filterByWmsGetCapabilities
- minimumMaxScaleDenominator
- allowEntireWmsServers

**Comment by nf-s** [comment]
## PacificMap

We can ignore CSV errors - those layers are replaced by SDMX

### CKAN

- includeCsv
- includeGeoJson
- includeKml
- includeWms
- includeWfs
- includeEsriMapServer
- includeEsriFeatureServer
- filterByWmsGetCapabilities
- minimumMaxScaleDenominator
- allowEntireWmsServers

**Comment by nf-s** [comment]
@na9da :
>So except for the CKAN & pacific map CSV and a few that I have marked - all the others need porting.

**Comment by soyarsauce** [comment]
>id ?

Will likely be incorporated in some way via https://github.com/terriajs/terriajs/issues/4774

**Comment by nf-s** [comment]
I have written a big list of properties needed for `WMS` conversion - https://github.com/TerriaJS/catalog-converter/issues/12

**Comment by nf-s** [comment]
## Other catalog types needed for pacific map (through CKAN)

- CSV
- GeoJSON

## CKAN issues

- Nested groups
- WMS groups...

**Comment by nf-s** [comment]
New notification

<img src="https://user-images.githubusercontent.com/6187649/94540485-ddce6c00-0289-11eb-8f50-b799111da3c6.png " width="500px"/>

**Comment by nf-s** [comment]
Change "Warning" to "Notice"
Change "Warnings" to "Technical details"

See [Share migration - warning text update issue](https://github.com/TerriaJS/terriajs/issues/4875)

**Comment by soyarsauce** [comment]
(for @steve9164)
3 ways for share fixes in saas
- v7-v8 catalog conversion. as long as you never want to change. no catalog editor.
- fix share keys, with alias IDs.
- actually fixed being able to move things. "full instant v8 catalog". or the magda-terria-api

**Comment by nf-s** [comment]
Note `initializationUrls` aren't dealt with at the moment. They are passed from v7-v8 shares, but v8 `terriajs` can't do anything with a v7 `initializationUrl`

**Comment by nf-s** [comment]
I'm going to close this, and turn all remaining tasks into separate issues.
This is closed by https://github.com/TerriaJS/catalog-converter/pull/11

**Comment by nf-s** [comment]
Id issue temporarily solved by https://github.com/TerriaJS/terriajs/pull/4887
