### ISSUE TITLE
Client-side vector support

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4633]
Terria/Cesium's client-side vector support is not ideal.

## Why

- Lots of features / highly complex features will crash the browser
- In a lot of cases WMS for vector datasets use more bandwidth, are slow and ugly.
  - And we may be able to eliminate Geoserver from a few deployments
- Render place names/roads on top of raster layers (in a nice way)
- 3D/Rotation support for text/labels
- Having features client-side means we can do interactive styling/filtering, and also "analytics"
- Vector tiles are beautiful (I mean seriously):
  - [Mapbox](https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#6.23/-36.014/148.493)
  - [Google maps](https://www.google.com/maps/@-42.9063249,147.3127389,18404a,35y,5.77h/data=!3m1!1e3)

## What we need:

- [x] - Mvt support for all geometry types
- [x] - use geojson-vt for large geojson layers
- [x] - property-based styling (something like mapbox style/expressions)

## What would be nice:

- [x] - zipped file support
- [x] - Shapefile support
- [x] - Vector features rendered ~as nicely as mapbox gl~ (not quite as nice, but good enough for the moment)
- Deckgl style data vis layers - https://deck.gl/examples/screen-grid-layer/

## Example use cases:

- [x] - 100MB of geojson
- [x] - Road network vector tile layer
- [x]   - Style road network by attribute (eg speed)
- [x] - Place names vector tile layer
- [x] - Show 500,000 2D points
- [x]   - Style points by attribute
- [ ]   - Cluster points by zoom level
- [ ] - Animated (time-series) 50,000 points
- [x] - MVT basemap?

## Related issues:

- [x] - Shapefile support https://github.com/TerriaJS/terriajs/issues/3082
- [x] - MVT geometry type support https://github.com/TerriaJS/terriajs/issues/3846
- [ ] - Tiling WFS https://github.com/TerriaJS/terriajs/issues/3661
- [ ] - Improve vt docs https://github.com/TerriaJS/terriajs/issues/2836
- [ ] - Warn user about large geojson files https://github.com/TerriaJS/terriajs/issues/2638
- [x] - Opacity https://github.com/TerriaJS/terriajs/issues/1442
- [x] - Marker spec https://github.com/TerriaJS/terriajs/issues/1089
- [x] - Styling vector https://github.com/TerriaJS/terriajs/issues/574
- [x] - Legends for styled vector https://github.com/TerriaJS/terriajs/issues/1353
- ... more to come

## Related PRs:

- Mobxify mvt catalog item #4151

**Comment by KeyboardSounds** [comment]
I think the easiest way to implement this is to convert things into 3dtiles' vector tiles format on the fly in the browser if we can. That way, we take advantage of Cesium's existing rendering code rather than having to write our own.

Oh, but a little birdy told me that the 3d tiles vector format is going to change in the next few months, so we should wait for that.

**Comment by KeyboardSounds** [comment]
This: https://github.com/CesiumGS/cesium/issues/9102 might also improve vector performance a bit.

**Comment by nf-s** [comment]
Potential ways forward:

get `geojson-vt` converting geojson to mvt on the fly, then improve mvt support by either:
- improve mvtImageryProvider:
  - Add line/point support
  - Add basic styling - like continuous colour scale
- Look into loaders/deck.gl mvt renderer:
  - Shove it into an imagery provider
  - Get everything for free (+ support for other deck.gl layers)
- Look into Cesium's vector tiles and write a converter


my vote is on trying loaders/deck.gl - it is quite a small dependency - and if it works we'd get a heap of other good stuff

**Comment by KeyboardSounds** [comment]
Related: https://github.com/TerriaJS/terriajs/issues/5513

**Comment by nf-s** [comment]
https://github.com/TerriaJS/terriajs/pull/5736 has been merged - this adds MVT support through protomapsjs

**Comment by AnaBelgun** [comment]
TODO next: 
- dynamic styling - @nf-s to write ticket / connect to this

**Comment by nf-s** [comment]
I'm going to close this for the moment, majority of tasks have been completed
