### ISSUE TITLE
[EPIC] Add (User) data problems

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4634]
```[tasklist]
### Tasks
- [ ] https://github.com/TerriaJS/terriajs/issues/6567
- [ ] https://github.com/TerriaJS/terriajs/issues/4615
- [ ] https://github.com/TerriaJS/terriajs/issues/4441
- [ ] https://github.com/TerriaJS/terriajs/issues/4645
- [ ] https://github.com/TerriaJS/terriajs/issues/4285
- [ ] https://github.com/TerriaJS/terriajs/issues/4295
- [ ] https://github.com/TerriaJS/terriajs/issues/1208
- [ ] https://github.com/TerriaJS/terriajs/issues/4909
```
