### ISSUE TITLE
[EPIC] Better automatic region-mapping

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4690]
A few things:

- [ ] - Ability to guess region type from column values alone
- [ ] - If there are multiple columns with regionType - use the one which highest number of matches and smallest regions (highest level of detail)
- [x] - Way to enable manual region mapping through UI?
- [ ] - Warn if regions are unrecognised
- [ ] - I will add more as I think of them...

**Comment by KeyboardSounds** [comment]
+1 for
> If there are multiple columns with regionType - use the one which highest number of matches and smallest regions (highest level of detail)

Also, when there are multiple region columns, we should let the user pick which one to show
