### ISSUE TITLE
Support new OGC APIs

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4763]
https://ogcapi.ogc.org/

- Maps (WMS replacement)
- Features (WFS replacement)
- Processes (WPS replacement)
- Coverage (WCS replacement)
- Records (catalog thing)
- ...

Currently the only standard in version 1 is core Features - everything else is draft
```[tasklist]
### Tasks
- [ ] https://github.com/TerriaJS/terriajs/issues/6803
- [ ] https://github.com/TerriaJS/terriajs/issues/6804
- [ ] https://github.com/TerriaJS/terriajs/issues/6805
- [ ] https://github.com/TerriaJS/data-registry/issues/207
- [ ] https://github.com/TerriaJS/terriajs/issues/6907
```

**Comment by AnaBelgun** [comment]
will convert to epics when new APIs are approved new versions of std

**Comment by geekdenz** [comment]
I am interested in contributing to this as my employer has expressed interest in this functionality and could potentially fund my involvement and contribution to this FOSS4G standards project.

If you are too, please get in touch so we don't double any work.

**Comment by geospatialmapmashup** [comment]
We are very interested in this as we do work for the US Government and they are requesting OGC API Features and OGC API Tiles and OGC GeoVolumes API

**Comment by AnaBelgun** [comment]
hi @geospatialmapmashup and @geekdenz thank you for expressing interest in this. Unfortunately although we are keen to develop the support, it's not currently on our high priority list. Should you wish to invest in building the support, we're more than happy to review the PRs and discuss the approach.

**Comment by geekdenz** [comment]
hi @AnaBelgun and @geospatialmapmashup 

Thanks for your quick responses. To be clear my interest is in contributing the development of this. My employer would be the sponsor since we have a vested interest in open standards.

I am merely communicating that if we're all lucky and I can do this reasonably quickly according to my estimate, that I can go ahead with the implementation of this having the privilege of being sponsored by my employer.

Also, I'd like to be clear that I just want to ensure no one else has done or is currently doing this. If it has been done, please let me know in this issue.

If someone is currently already working on this, please reach out so we can collaborate.

**Comment by AnaBelgun** [comment]
Hi @geekdenz thanks, We're definitely not working on this atm.

**Comment by hakoncarlsen** [comment]
hi @geekdenz 

Did you start working on this?

**Comment by geekdenz** [comment]
Sorry, @AnaBelgun and @hakoncarlsen .

My situation has changed and I do not have time to work on this currently. There might be a time when I would have time to look into this but for now, please don't hesitate to have someone else do this.

**Comment by hakoncarlsen** [comment]
Allright, thanks for you response @geekdenz .

**Comment by rsignell** [comment]
Just for fun, here is a nice demo of the OGC API Tile Service: https://flux-web-demo.vercel.app/gfs-globe-tiles, with tiles being supplied by the new open source "xpublish-tiles" package. 

Blog post: https://earthmover.io/blog/dynamic-map-tile-rendering-icechunk-zarr-data-xpublish-tiles

Repo: https://github.com/earth-mover/flux-web-demo

Requests look like this: https://compute.earthmover.io/v1/services/tiles/earthmover-public/gfs/main/solar/tiles/WebMercatorQuad/2/1/1?&variables=t2m&colorscalerange=270,320&width=512&height=512&style=raster/jet&time=2025-10-01T00:00:00Z&step=0%20hours
