### ISSUE TITLE
[EPIC] Mobile support improvements

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5765]
There are some issues with the mobile support for v8. 

All apps: 
- Bottom menu not showing (unless you swipe upwards starting from the main navigation bar at the bottom of the phone screen)
- redraft landing page popup; i.e. "Dive right in and get started or check the following help guide options" 
- Redraft landing page message to include a reference to not being ideal for visualising a large nr of data overlayed, or 3D data, charts etc etc 
- add Zoom reset at the bottom
- Remove 3d item search from the context menu in mobile view

Digital Twins:
- when showing, you cannot click on the middle buttons (i.e. when trying to click on Compare, the Measuring Tool appears)
- remove scene editor button 
- add Gyroscope (TBC)

NationalMap/TerriaMaps
- when bottom menu showing, measuring tool is covered by Feedback button etc.

Update 2 Sep 2021: 
- Issues refined and broken down following[ this](https://miro.com/app/board/o9J_lzzMfHU=/)
- [x] https://github.com/TerriaJS/terriajs/issues/4670
- [x] https://github.com/terriajs/nationalmap/issues/1056
- [x] https://github.com/terriajs/terriajs/issues/5780
- [x] https://github.com/TerriaJS/terriajs/issues/5794
- [x] https://github.com/terriajs/terriajs/issues/5782
- [x] https://github.com/terriajs/terriajs/issues/5787
- [x] https://github.com/terriajs/terriajs/issues/5785
- [x] https://github.com/terriajs/terriajs/issues/5791
- [x] https://github.com/terriajs/terriajs/issues/5779
- [x] https://github.com/terriajs/terriajs/issues/5783
- [x] https://github.com/terriajs/terriajs/issues/5789
- [x] https://github.com/terriajs/nationalmap/issues/1058
- [x] https://github.com/TerriaJS/terriajs/issues/5806
- [ ] https://github.com/terriajs/terriajs/issues/5786
- [ ] https://github.com/terriajs/terriajs/issues/5792
- [x] https://github.com/terriajs/terriajs/issues/5790
- [x] https://github.com/terriajs/terriajs/issues/5781
- [x] https://github.com/terriajs/terriajs/issues/5788
- [x] https://github.com/terriajs/terriajs/issues/5784
- [x] https://github.com/terriajs/nationalmap/issues/1057

**Comment by zoran995** [comment]
> * [ ]  Bottom menu not showing (unless you swipe upwards starting from the main navigation bar at the bottom of the phone screen)

#4850 should resolve this point (we are using it without any issues)

**Comment by AnaBelgun** [comment]
thank you @zoran995 that's amazing

**Comment by AnaBelgun** [comment]
Action: stocktake list of what is available on mobile in Digital Twins and Terria Maps

**Comment by AnaBelgun** [comment]
Terria Maps: 


Digital Twins:

**Comment by wibily** [comment]
Phil to refine this ticket and split up afterwards between @derp and @na9da

**Comment by wibily** [comment]
ticket has been broken down and refined

**Comment by zoran995** [comment]
> * [ ]  when showing, you cannot click on the middle buttons (i.e. when trying to click on Compare, the Measuring Tool appears)

Forgot to mention this is resolved in #5062

**Comment by AnaBelgun** [comment]
Following release of TerriaJS end of Sep: 
- make this an epic
- refine the tickets
- link each ticket to a section in the new mobile design
