### ISSUE TITLE
Mobile: Disable (some) features 

### ISSUE THREAD

**Issue by wibily** [TerriaJS/terriajs#5779]
Some features do not work properly for mobile, this ticket is to disable them until we build in proper support for them at a later stage

- [ ] ~Compare (also see #5781)~
- [x] Difference (already hidden)
- [x] Scene editor (also https://github.com/TerriaJS/product/issues/103) - PR in NSW DT Repo 
- [x] feature search (#5800)
- [x] upload data (this is already the case - in mobile add data menu does not have an option to upload local data or add data by url).
- [x] compass/gyro (fixed by #5062)
- [x] location filter (time series) (#5800 introduces an easy fix to make this work in mobile)
- [x] export (clip & ship) (#5800)
- [x] pedestrian mode (fixed by #5062)

**Comment by zoran995** [comment]
can you provide more details on compare don't work properly on mobile, as I recall everything worked correctly on our end, and everything still seems to work?

**Comment by wibily** [comment]
> can you provide more details on compare don't work properly on mobile, as I recall everything worked correctly on our end, and everything still seems to work?

@zoran995 I've just double checked it on mobile and it does indeed work. Our concern was that the workflow in mobile was a bit clunky with the controls for the compare hidden inside the eye icon. @philipgrimmett Perhaps a compromise will be to remove the button in the map controls, add in a prominent "exit compare" button as part of #5781 but leave it in the dotted menu in the workbench as an advanced feature?

**Comment by AnaBelgun** [comment]
Hi @zoran995 another consideration is to "hide" the features because they are not designed yet for mobile, but to leave them available to use if you share a story for example i.e. when you access a share link or a story with one of the hidden features like Compare, you can still see the splitter line and move it across etc. 

Do you have other thoughts on this?
