### ISSUE TITLE
v7-v8 - NatMap / CKAN migration 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5893]
- [x] CKAN catalogue unknown properties: allowEntireWmsServers: add support in v8 for WMS server; related to the problem of WMS layers and how they are turned into groups: https://github.com/TerriaJS/terriajs/issues/5745
- [x] <ins>"itemProperties": 1 **Not implemented in v8 for CatalogGroupMixin** https://github.com/TerriaJS/terriajs/issues/5155</inss
- [x] <ins> "itemProperties": 1, **Not implemented in v8 for this catalog item** https://github.com/TerriaJS/terriajs/issues/5155</ins>
- [ ]  ~<ins>"getFeatureInfoFormats": 4, **Not Implemented in v8*** https://github.com/TerriaJS/terriajs/issues/5163</ins>~ Not CKAN
- [ ] ~CsvCatalogItem: unknown properties  - charSet: 2 datasets affected - https://github.com/TerriaJS/terriajs/issues/5747~ not CKAN
- [x] CKAN catalogue unknown properties: useResourceName - https://github.com/TerriaJS/terriajs/issues/5749
- [ ] ~CKAN unknown properties: minimumMaxScaleDenominator - https://github.com/TerriaJS/terriajs/issues/5748~ Not CKAN
- [ ] ~<ins>"ignoreUnknownTileErrors": 79,  **Not implemented in v8 for this catalog item** https://github.com/TerriaJS/terriajs/issues/5154</ins> - @na9da did the WMS~ Not CKAN
- [ ]  ~"treat403AsError": 1 **Not implemented in v8 for this catalog item** https://github.com/TerriaJS/terriajs/issues/5154~ Not CKAN
- [ ] ~<ins> "showWarnings": 4 **Not implemented in v8 for this catalog item** </ins>  - https://github.com/terriajs/terriajs/issues/5459~ Not CKAN

**Comment by nf-s** [comment]
All CKAN relevant tickets are closed
