### ISSUE TITLE
[EPIC]: Printing v3.0

### ISSUE THREAD

**Issue by wibily** [TerriaJS/terriajs#6122]
Todo:
- [ ] Initial popup blocker stops initial showing of print view
- [x] Show print view button does not work if the print view window is still open
- [x] QR code library has size limits - QR library removed
- [x] Legend does not scale correctly with the image
- [ ] Compass is missing
- [x] Legends are not aligned with the map
- [ ] Map image, CSV/JSON download buttons are missing
- [ ] Dataset checkbox/Collapse controls are not yet implmented
- [ ] Elements are overall not styled correctly
- [ ] Time formating not great
- [ ] Share link does not regenerate correctly

For more details, please see original ticket: terriajs#5490

**Comment by wibily** [comment]
@philipgrimmett New ticket for printing created here

**Comment by nf-s** [comment]
- [ ] Add feature info
