### ISSUE TITLE
[Epic] Story v3.0 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6249]
The next version of the Story functionality will include remaining items from v2.0 + other enhancements. 
This epic is to track all these tickets. 

Remaining items from v2.0

- [ ] https://github.com/TerriaJS/terriajs/issues/3279
- [x] https://github.com/TerriaJS/terriajs/issues/5595
- [ ] https://github.com/TerriaJS/terriajs/issues/5596
- [ ] https://github.com/TerriaJS/terriajs/issues/5228
- [ ] https://github.com/TerriaJS/terriajs/issues/4210
- [ ] https://github.com/TerriaJS/terriajs/issues/5597
- [ ] https://github.com/TerriaJS/terriajs/issues/5463
- [ ] https://github.com/TerriaJS/saas-feedback/issues/192

**Comment by AnaBelgun** [comment]
Closing in favour of new epics.
