### ISSUE TITLE
[EPIC] Terria JS Version 9 release

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6308]
- [ ] https://github.com/TerriaJS/terriajs/issues/6227
- [ ] https://github.com/TerriaJS/terriajs/issues/6226
- [ ] https://github.com/TerriaJS/terriajs/pull/5918
- [ ] https://github.com/TerriaJS/terriajs/issues/4741
- [ ] ...
