### ISSUE TITLE
Implement ESBuild

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#6624]
This is a ticket to track esbuild testing. It is very experimental and perhaps a long way off from standing on its feet.

@kring started a branch [here](https://github.com/TerriaJS/TerriaMap/tree/esbuild) and [here](https://github.com/TerriaJS/terriajs/tree/esbuild) to test out esbuild. I have added some of my own changes to get sass+css-modules partially working.

TODOs:
- [x] sass+css-modules partially working
- [x] jsx-control-statements working using babel
- [ ]  De-duplicate + minify generated class names and fix the broken styles
- [ ] Get sourcemaps working
- [ ] Extract `.css` for production builds
- [x] Get cesium map working (without cheating)
- [x] Find a solution for super-get. In terria v8 we replace babel's version of `super` with one that is mobx aware. We should either avoid the need for it (basically remove all instances of overriding `@computed` getters) or do the same replacement for esbuild generated code.
- [ ] Get icons working
- [ ] Build time with sass is 5secs, see if we can improve it.
- [ ] Test with plugins (icon packaging etc.)
- [ ] Broken tests
   - [x] https://github.com/TerriaJS/terriajs/issues/6834
   - [ ] TileHandlerErrorMixin (3) - depends on some changes in our Cesium fork
   - [ ] ArcGisMapServerCatalogItem (1) - Another dependency on our fork - missing `parameters` property in `ArcGisImageryProvider`
   - [ ] AssimpCatalogItem (3) - Something to do with assimpjs wasm binaries not loading (have to copy the wasm files during build like we do in webpack)
   - [ ] ShapefileCatalogItem (2) - Error when importing `@mapbox/geojson-merge`
   - [ ] Fix new errors after upgrade to Cesium `1.108`
- [ ] Broken datasets:
  - [ ] The CZML with glTF catalog items in the [default catalog](http://ci.terria.io/main/#start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22%2F%2FSmall+glTF+3D+Models%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%5D%2C%22timeline%22%3A%5B%5D%2C%22initialCamera%22%3A%7B%22west%22%3A96.61240309448937%2C%22south%22%3A-41.201929081333155%2C%22east%22%3A170.38759712226664%2C%22north%22%3A-4.673078992570755%2C%22position%22%3A%7B%22x%22%3A-7624597.9392026225%2C%22y%22%3A8034649.771589909%2C%22z%22%3A-5509082.03296846%7D%2C%22direction%22%3A%7B%22x%22%3A0.6155066295087045%2C%22y%22%3A-0.6486086531549473%2C%22z%22%3A0.44772581351018803%7D%2C%22up%22%3A%7B%22x%22%3A-0.3081941123859461%2C%22y%22%3A0.3247688303609176%2C%22z%22%3A0.8941708986075539%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223d%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.5%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A1%2C%22useNativeResolution%22%3Afalse%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-bing-aerial-with-labels%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22previewedItemId%22%3A%22%2F%2FSmall+glTF+3D+Models%22%2C%22stories%22%3A%5B%5D%7D%5D%7D).
- [ ] Broken features
  - [ ] Pedestrian mode (keyboard navigation not working)

**Comment by na9da** [comment]
Current status (with some cheating):
![image](https://user-images.githubusercontent.com/1430/201548362-68b9b544-60fc-4a0e-a05b-4196f4882a62.png)

![image](https://user-images.githubusercontent.com/1430/201548374-811a2e26-f51a-4cc0-9123-e483ccf761ba.png)

**Comment by tephenavies** [comment]
Include a comparison with https://github.com/swc-project/swc to see which to use.

**Comment by AnaBelgun** [comment]
- TS PR created and it's being reviewed with no certain timeline 
- assuming it's merged
- worked on other outstanding issues: i.e. specs

**Comment by AnaBelgun** [comment]
Update 27 Sep 23
- Nanda to pick one issue like fixing the icon

**Comment by AnaBelgun** [comment]
here @kring @na9da will list the inventory following the structure of done+ extract work and to-be-done
