### ISSUE TITLE
TerriaJS release `8.3.6`

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6912]
```[tasklist]
### Tasks
- [ ] https://github.com/TerriaJS/terriajs/pull/6915
- [ ] https://github.com/TerriaJS/terriajs/issues/6913
- [ ] https://github.com/TerriaJS/terriajs/pull/6914
```

**Comment by ronitpatel1** [comment]
@AnaBelgun here is our teams feedback - we are okay with the latest update here are some observations: 

1. Site Loading Issues:
•	Australian Gannets (Popes Eye) Summer 2014-15
•	Error Received: "Aw snap – Something went wrong when displaying this web page (out of memory)"

6. Performance Issues:
•	(General observation) Performance appears to have gotten worse since the update with increased load times.  
•	(General observation) The ideal zoom takes longer than usual to activate.

Other issues identified during testing: 

Layer Issue:
•	URL: [Vicplan Planning Scheme Overlays](https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeOverlays/MapServer/3) (ALL layers within this group) 
•	Feedback: These layers do not have an ideal zoom in either the prod or test environment.
 Issue with Pedestrian Mode:
•	Feedback: When in pedestrian mode, the user inadvertently grabs the models and adjusts the camera position. The expected "click and hold" feature of the mouse doesn't function properly. This issue is consistently present in the prod environment regardless of the datasets loaded.

**Comment by AnaBelgun** [comment]
Hi @ronitpatel1 thank you for the feedback. 
We will add those into the next release, unless there's something urgent we need to look into.
